import './globals.css';
import Navbar from './components/Navbar/index';
import Footer from './components/Footer/index';
import AnimatedDollar from './components/AnimatedDollar/index';

export const metadata = {
  title: 'FinanceProTricks',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <AnimatedDollar />
        <Footer />
      </body>
    </html>
  )
}
